-- INSERT USERS
INSERT INTO client (names, lastnames, phone, email, password) VALUES ('William', 'Martinez', '0998074949', 'mwilliam1412@gmail.com', '$2a$10$zwlqcCShwUlaOhcUC8e2cuOIZjiJJrEib9jZck./ecWAVAElbcjIy');
INSERT INTO client (names, lastnames, phone, email, password) VALUES ('Ana', 'García', '555-2222', 'ana@example.com', '$2a$10$zwlqcCShwUlaOhcUC8e2cuOIZjiJJrEib9jZck./ecWAVAElbcjIy');
INSERT INTO client (names, lastnames, phone, email, password) VALUES ('Luis', 'Martínez', '555-3333', 'luis@example.com', '$2a$10$zwlqcCShwUlaOhcUC8e2cuOIZjiJJrEib9jZck./ecWAVAElbcjIy');

-- INSERT PROJECTS
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U1_1', 'Descripción del Proyecto U1_1', 1);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U1_2', 'Descripción del Proyecto U1_2', 1);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U1_3', 'Descripción del Proyecto U1_3', 1);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U1_4', 'Descripción del Proyecto U1_4', 1);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U1_5', 'Descripción del Proyecto U1_5', 1);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_1', 'Descripción del Proyecto U2_1', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_2', 'Descripción del Proyecto U2_2', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_3', 'Descripción del Proyecto U2_3', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_4', 'Descripción del Proyecto U2_4', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_5', 'Descripción del Proyecto U2_5', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_6', 'Descripción del Proyecto U2_6', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U2_7', 'Descripción del Proyecto U2_7', 2);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_1', 'Descripción del Proyecto U3_1', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_2', 'Descripción del Proyecto U3_2', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_3', 'Descripción del Proyecto U3_3', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_4', 'Descripción del Proyecto U3_4', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_5', 'Descripción del Proyecto U3_5', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_6', 'Descripción del Proyecto U3_6', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_7', 'Descripción del Proyecto U3_7', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_8', 'Descripción del Proyecto U3_8', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_9', 'Descripción del Proyecto U3_9', 3);
INSERT INTO project ( name, description, client_id) VALUES ('Proyecto U3_10', 'Descripción del Proyecto U3_10', 3);

-- INSERT TASKS
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P1_1', 'Descripción de Tarea P1_1', FALSE, 1);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P1_2', 'Descripción de Tarea P1_2', FALSE, 1);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P1_3', 'Descripción de Tarea P1_3', TRUE, 1);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P1_4', 'Descripción de Tarea P1_4', TRUE, 1);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P1_5', 'Descripción de Tarea P1_5', TRUE, 1);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P1_6', 'Descripción de Tarea P1_6', FALSE, 1);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_1', 'Descripción de Tarea P2_1', FALSE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_2', 'Descripción de Tarea P2_2', TRUE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_3', 'Descripción de Tarea P2_3', FALSE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_4', 'Descripción de Tarea P2_4', FALSE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_5', 'Descripción de Tarea P2_5', TRUE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_6', 'Descripción de Tarea P2_6', TRUE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P2_7', 'Descripción de Tarea P2_7', TRUE, 2);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P3_1', 'Descripción de Tarea P3_1', FALSE, 3);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P3_2', 'Descripción de Tarea P3_2', TRUE, 3);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P3_3', 'Descripción de Tarea P3_3', FALSE, 3);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P3_4', 'Descripción de Tarea P3_4', TRUE, 3);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P3_5', 'Descripción de Tarea P3_5', FALSE, 3);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P4_1', 'Descripción de Tarea P4_1', TRUE, 4);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P4_2', 'Descripción de Tarea P4_2', FALSE, 4);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P4_3', 'Descripción de Tarea P4_3', FALSE, 4);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P4_4', 'Descripción de Tarea P4_4', FALSE, 4);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P4_5', 'Descripción de Tarea P4_5', FALSE, 4);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P5_1', 'Descripción de Tarea P5_1', FALSE, 5);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P5_2', 'Descripción de Tarea P5_2', TRUE, 5);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P5_3', 'Descripción de Tarea P5_3', FALSE, 5);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P5_4', 'Descripción de Tarea P5_4', FALSE, 5);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P5_5', 'Descripción de Tarea P5_5', TRUE, 5);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P5_6', 'Descripción de Tarea P5_6', FALSE, 5);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P6_1', 'Descripción de Tarea P6_1', TRUE, 6);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P6_2', 'Descripción de Tarea P6_2', FALSE, 6);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P6_3', 'Descripción de Tarea P6_3', FALSE, 6);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P6_4', 'Descripción de Tarea P6_4', TRUE, 6);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_1', 'Descripción de Tarea P7_1', TRUE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_2', 'Descripción de Tarea P7_2', TRUE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_3', 'Descripción de Tarea P7_3', TRUE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_4', 'Descripción de Tarea P7_4', FALSE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_5', 'Descripción de Tarea P7_5', TRUE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_6', 'Descripción de Tarea P7_6', FALSE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_7', 'Descripción de Tarea P7_7', FALSE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_8', 'Descripción de Tarea P7_8', TRUE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P7_9', 'Descripción de Tarea P7_9', FALSE, 7);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_1', 'Descripción de Tarea P8_1', TRUE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_2', 'Descripción de Tarea P8_2', TRUE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_3', 'Descripción de Tarea P8_3', FALSE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_4', 'Descripción de Tarea P8_4', FALSE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_5', 'Descripción de Tarea P8_5', FALSE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_6', 'Descripción de Tarea P8_6', TRUE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_7', 'Descripción de Tarea P8_7', TRUE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_8', 'Descripción de Tarea P8_8', TRUE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_9', 'Descripción de Tarea P8_9', FALSE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P8_10', 'Descripción de Tarea P8_10', FALSE, 8);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P9_1', 'Descripción de Tarea P9_1', TRUE, 9);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P9_2', 'Descripción de Tarea P9_2', TRUE, 9);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_1', 'Descripción de Tarea P10_1', FALSE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_2', 'Descripción de Tarea P10_2', FALSE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_3', 'Descripción de Tarea P10_3', TRUE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_4', 'Descripción de Tarea P10_4', FALSE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_5', 'Descripción de Tarea P10_5', FALSE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_6', 'Descripción de Tarea P10_6', TRUE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_7', 'Descripción de Tarea P10_7', FALSE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P10_8', 'Descripción de Tarea P10_8', FALSE, 10);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P11_1', 'Descripción de Tarea P11_1', FALSE, 11);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P11_2', 'Descripción de Tarea P11_2', FALSE, 11);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P12_1', 'Descripción de Tarea P12_1', TRUE, 12);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P12_2', 'Descripción de Tarea P12_2', TRUE, 12);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P12_3', 'Descripción de Tarea P12_3', FALSE, 12);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P13_1', 'Descripción de Tarea P13_1', TRUE, 13);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P13_2', 'Descripción de Tarea P13_2', FALSE, 13);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P13_3', 'Descripción de Tarea P13_3', FALSE, 13);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P13_4', 'Descripción de Tarea P13_4', TRUE, 13);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P13_5', 'Descripción de Tarea P13_5', FALSE, 13);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_1', 'Descripción de Tarea P14_1', TRUE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_2', 'Descripción de Tarea P14_2', FALSE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_3', 'Descripción de Tarea P14_3', TRUE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_4', 'Descripción de Tarea P14_4', FALSE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_5', 'Descripción de Tarea P14_5', FALSE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_6', 'Descripción de Tarea P14_6', FALSE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_7', 'Descripción de Tarea P14_7', TRUE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P14_8', 'Descripción de Tarea P14_8', FALSE, 14);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P15_1', 'Descripción de Tarea P15_1', FALSE, 15);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P15_2', 'Descripción de Tarea P15_2', TRUE, 15);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P15_3', 'Descripción de Tarea P15_3', TRUE, 15);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P15_4', 'Descripción de Tarea P15_4', FALSE, 15);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_1', 'Descripción de Tarea P16_1', TRUE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_2', 'Descripción de Tarea P16_2', FALSE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_3', 'Descripción de Tarea P16_3', FALSE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_4', 'Descripción de Tarea P16_4', TRUE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_5', 'Descripción de Tarea P16_5', FALSE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_6', 'Descripción de Tarea P16_6', FALSE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P16_7', 'Descripción de Tarea P16_7', TRUE, 16);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_1', 'Descripción de Tarea P17_1', TRUE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_2', 'Descripción de Tarea P17_2', FALSE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_3', 'Descripción de Tarea P17_3', TRUE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_4', 'Descripción de Tarea P17_4', FALSE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_5', 'Descripción de Tarea P17_5', TRUE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_6', 'Descripción de Tarea P17_6', TRUE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_7', 'Descripción de Tarea P17_7', FALSE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_8', 'Descripción de Tarea P17_8', FALSE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_9', 'Descripción de Tarea P17_9', FALSE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P17_10', 'Descripción de Tarea P17_10', TRUE, 17);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_1', 'Descripción de Tarea P18_1', TRUE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_2', 'Descripción de Tarea P18_2', TRUE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_3', 'Descripción de Tarea P18_3', FALSE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_4', 'Descripción de Tarea P18_4', FALSE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_5', 'Descripción de Tarea P18_5', TRUE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_6', 'Descripción de Tarea P18_6', TRUE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_7', 'Descripción de Tarea P18_7', FALSE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P18_8', 'Descripción de Tarea P18_8', TRUE, 18);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P19_1', 'Descripción de Tarea P19_1', FALSE, 19);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P19_2', 'Descripción de Tarea P19_2', TRUE, 19);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P19_3', 'Descripción de Tarea P19_3', FALSE, 19);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P19_4', 'Descripción de Tarea P19_4', TRUE, 19);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P19_5', 'Descripción de Tarea P19_5', TRUE, 19);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_1', 'Descripción de Tarea P20_1', FALSE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_2', 'Descripción de Tarea P20_2', FALSE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_3', 'Descripción de Tarea P20_3', TRUE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_4', 'Descripción de Tarea P20_4', FALSE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_5', 'Descripción de Tarea P20_5', FALSE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_6', 'Descripción de Tarea P20_6', TRUE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_7', 'Descripción de Tarea P20_7', TRUE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_8', 'Descripción de Tarea P20_8', TRUE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P20_9', 'Descripción de Tarea P20_9', FALSE, 20);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_1', 'Descripción de Tarea P21_1', TRUE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_2', 'Descripción de Tarea P21_2', FALSE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_3', 'Descripción de Tarea P21_3', FALSE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_4', 'Descripción de Tarea P21_4', FALSE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_5', 'Descripción de Tarea P21_5', FALSE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_6', 'Descripción de Tarea P21_6', TRUE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_7', 'Descripción de Tarea P21_7', TRUE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_8', 'Descripción de Tarea P21_8', TRUE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P21_9', 'Descripción de Tarea P21_9', FALSE, 21);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P22_1', 'Descripción de Tarea P22_1', TRUE, 22);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P22_2', 'Descripción de Tarea P22_2', FALSE, 22);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P22_3', 'Descripción de Tarea P22_3', FALSE, 22);
INSERT INTO task (title, description, state, project_id) VALUES ('Tarea P22_4', 'Descripción de Tarea P22_4', FALSE, 22);